### ISSUE TITLE
Administrators of a survey can hide a question 

### ISSUE THREAD

**Issue by rdarin** [pegasystems/building-bridges#6]
It would be nice to give Admins the ability to set their own "Code of Conduct" for a survey at create time and then allow them to enforce that code of conduct when the survey is taking place.

Ideas for how:
**At survey creation**
At survey creation time there is a new checkbox for "Include a code of conduct section". If that checkbox is checked, the creator is able to add free form text that will be displayed below the header of their survey.

**On admin page**
A "eye" appears on the right side of submissions. If the Admin clicks the "eye" it switches to slash through eye icon and the question background has slashes through it to indicate it is hidden like this https://css-tricks.com/stripes-css/

**on active survey**
-code of conduct is shown at the top
-questions hidden on admin view are not shown at all

**on locked survey**
-questions hidden on admin view are not shown at all

**Comment by dcasavant** [comment]
Just a suggestion - what if the violation questions were hidden in a collapsed section at the bottom, labeled as such, and locked (no votes allowed)?  That way the action would be transparent but still enforced (like when Google removes links that violate the DMCA).  

Maybe this would just be an option depending on the question and level of enforcement required...

**Comment by Wowol** [comment]
Done in #9
