### ISSUE TITLE
Issue running app without docker

### ISSUE THREAD

**Issue by rdarin** [pegasystems/building-bridges#7]
Hello! I am trying to run and I followed the readme.. 

I tried on both Mac (preferred) and Ubuntu (to make sure it wasn't something I misread the first time and to make sure it wasn't mac specific)..
when I run 
`root@bridges-test:~/building-bridges# ./scripts/runBridges.sh`

I get the following error
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "bridges/__main__.py", line 1, in <module>
    from bridges.argument_parser import parse_args
ModuleNotFoundError: No module named 'bridges'
```

Has anyone else seen this? I will continue debugging, but wanted to share.

**Comment by rdarin** [comment]
Looking at the Dockerfile, I thought maybe I was missing `pip install --no-cache-dir -r requirements.txt` but even once I run that the script still fails with the same error.

**Comment by rdarin** [comment]
Continuing to diff from the Dockerfile I eventually ended up with the following in `scripts/runBridges.sh`
```
#!/bin/bash
./scripts/buildFrontEnd.sh
python3 -m pip install --no-cache-dir -r requirements.txt --user
python3 -m bridges
```
Does this seem like what it should be?

**Comment by pulnara** [comment]
Hi @rdarin, I came across the same problems today. I've fixed them in https://github.com/pegasystems/building-bridges/pull/5/commits/a1e4b657065b57f8002dba01165f91f5b603eb89 
When it comes to the `jinja2.exceptions.TemplateNotFound: index.html` error, it seems that template files are not properly copied in the `scripts/buildFrontEnd.sh` script, due to the order of arguments.

**Comment by rdarin** [comment]
It works! :) Thanks @pulnara

I present happy doggo as thanks 
![doggo](https://i.pinimg.com/originals/06/a4/c4/06a4c4f1d62a3be5bda9c097746705e9.jpg)
